#include "VulkanFormat.h"
#include "Utilities.h"

namespace VALX
{
    VkFormat ConvertFormatVulkan(Format format)
    {
        switch (format)
        {
        case VALX::Format::UNKNOWN:
            return VK_FORMAT_UNDEFINED;
        case VALX::Format::R4G4_UNORM_PACK8:
            return VK_FORMAT_R4G4_UNORM_PACK8;
        case VALX::Format::R4G4B4A4_UNORM_PACK16:
            return VK_FORMAT_R4G4B4A4_UNORM_PACK16;
        case VALX::Format::B4G4R4A4_UNORM_PACK16:
            return VK_FORMAT_B4G4R4A4_UNORM_PACK16; 
        case VALX::Format::R5G6B5_UNORM_PACK16:
            return VK_FORMAT_R5G6B5_UNORM_PACK16;
        case VALX::Format::B5G6R5_UNORM_PACK16:
            return VK_FORMAT_B5G6R5_UNORM_PACK16;
        case VALX::Format::R5G5B5A1_UNORM_PACK16:
            return VK_FORMAT_R5G5B5A1_UNORM_PACK16;
        case VALX::Format::B5G5R5A1_UNORM_PACK16:
            return VK_FORMAT_B5G5R5A1_UNORM_PACK16;
        case VALX::Format::A1R5G5B5_UNORM_PACK16:
            return VK_FORMAT_A1R5G5B5_UNORM_PACK16;
        case VALX::Format::R8_UNORM:
            return VK_FORMAT_R8_UNORM;
        case VALX::Format::R8_SNORM:
            return VK_FORMAT_R8_SNORM;
        case VALX::Format::R8_USCALED:
            return VK_FORMAT_R8_USCALED;
        case VALX::Format::R8_SSCALED:
            return VK_FORMAT_R8_SSCALED;
        case VALX::Format::R8_UINT:
            return VK_FORMAT_R8_UINT;
        case VALX::Format::R8_SINT:
            return VK_FORMAT_R8_SINT;
        case VALX::Format::R8_SRGB:
            return VK_FORMAT_R8_SRGB;
        case VALX::Format::R8G8_UNORM:
            return VK_FORMAT_R8G8_UNORM;
        case VALX::Format::R8G8_SNORM:
            return VK_FORMAT_R8G8_SNORM;
        case VALX::Format::R8G8_USCALED:
            return VK_FORMAT_R8G8_USCALED;
        case VALX::Format::R8G8_SSCALED:
            return VK_FORMAT_R8G8_SSCALED;
        case VALX::Format::R8G8_UINT:
            return VK_FORMAT_R8G8_UINT;
        case VALX::Format::R8G8_SINT:
            return VK_FORMAT_R8G8_SINT;
        case VALX::Format::R8G8_SRGB:
            return VK_FORMAT_R8G8_SRGB;
        case VALX::Format::R8G8B8_UNORM:
            return VK_FORMAT_R8G8B8_UNORM;
        case VALX::Format::R8G8B8_SNORM:
            return VK_FORMAT_R8G8B8_SNORM;
        case VALX::Format::R8G8B8_USCALED:
            return VK_FORMAT_R8G8B8_USCALED;
        case VALX::Format::R8G8B8_SSCALED:
            return VK_FORMAT_R8G8B8_SSCALED;
        case VALX::Format::R8G8B8_UINT:
            return VK_FORMAT_R8G8B8_UINT;
        case VALX::Format::R8G8B8_SINT:
            return VK_FORMAT_R8G8B8_SINT;
        case VALX::Format::R8G8B8_SRGB:
            return VK_FORMAT_R8G8B8_SRGB;
        case VALX::Format::B8G8R8_UNORM:
            return VK_FORMAT_B8G8R8_UNORM;
        case VALX::Format::B8G8R8_SNORM:
            return VK_FORMAT_B8G8R8_SNORM;
        case VALX::Format::B8G8R8_USCALED:
            return VK_FORMAT_B8G8R8_USCALED;
        case VALX::Format::B8G8R8_SSCALED:
            return VK_FORMAT_B8G8R8_SSCALED;
        case VALX::Format::B8G8R8_UINT:
            return VK_FORMAT_B8G8R8_UINT;
        case VALX::Format::B8G8R8_SINT:
            return VK_FORMAT_B8G8R8_SINT;
        case VALX::Format::B8G8R8_SRGB:
            return VK_FORMAT_B8G8R8_SRGB;
        case VALX::Format::R8G8B8A8_UNORM:
            return VK_FORMAT_R8G8B8A8_UNORM;
        case VALX::Format::R8G8B8A8_SNORM:
            return VK_FORMAT_R8G8B8A8_SNORM;
        case VALX::Format::R8G8B8A8_USCALED:
            return VK_FORMAT_R8G8B8A8_USCALED;
        case VALX::Format::R8G8B8A8_SSCALED:
            return VK_FORMAT_R8G8B8A8_SSCALED;
        case VALX::Format::R8G8B8A8_UINT:
            return VK_FORMAT_R8G8B8A8_UINT;
        case VALX::Format::R8G8B8A8_SINT:
            return VK_FORMAT_R8G8B8A8_SINT;
        case VALX::Format::R8G8B8A8_SRGB:
            return VK_FORMAT_R8G8B8A8_SRGB;
        case VALX::Format::B8G8R8A8_UNORM:
            return VK_FORMAT_B8G8R8A8_UNORM;
        case VALX::Format::B8G8R8A8_SNORM:
            return VK_FORMAT_B8G8R8A8_SNORM;
        case VALX::Format::B8G8R8A8_USCALED:
            return VK_FORMAT_B8G8R8A8_USCALED;
        case VALX::Format::B8G8R8A8_SSCALED:
            return VK_FORMAT_B8G8R8A8_SSCALED;
        case VALX::Format::B8G8R8A8_UINT:
            return VK_FORMAT_B8G8R8A8_UINT;
        case VALX::Format::B8G8R8A8_SINT:
            return VK_FORMAT_B8G8R8A8_SINT;
        case VALX::Format::B8G8R8A8_SRGB:
            return VK_FORMAT_B8G8R8A8_SRGB;
        case VALX::Format::A8B8G8R8_UNORM_PACK32:
            return VK_FORMAT_A8B8G8R8_UNORM_PACK32;
        case VALX::Format::A8B8G8R8_SNORM_PACK32:
            return VK_FORMAT_A8B8G8R8_SNORM_PACK32;
        case VALX::Format::A8B8G8R8_USCALED_PACK32:
            return VK_FORMAT_A8B8G8R8_USCALED_PACK32;
        case VALX::Format::A8B8G8R8_SSCALED_PACK32:
            return VK_FORMAT_A8B8G8R8_SSCALED_PACK32;
        case VALX::Format::A8B8G8R8_UINT_PACK32:
            return VK_FORMAT_A8B8G8R8_UINT_PACK32;
        case VALX::Format::A8B8G8R8_SINT_PACK32:
            return VK_FORMAT_A8B8G8R8_SINT_PACK32;
        case VALX::Format::A8B8G8R8_SRGB_PACK32:
            return VK_FORMAT_A8B8G8R8_SRGB_PACK32;
        case VALX::Format::A2R10G10B10_UNORM_PACK32:
            return VK_FORMAT_A2R10G10B10_UNORM_PACK32;
        case VALX::Format::A2R10G10B10_SNORM_PACK32:
            return VK_FORMAT_A2R10G10B10_SNORM_PACK32;
        case VALX::Format::A2R10G10B10_USCALED_PACK32:
            return VK_FORMAT_A2R10G10B10_USCALED_PACK32;
        case VALX::Format::A2R10G10B10_SSCALED_PACK32:
            return VK_FORMAT_A2R10G10B10_SSCALED_PACK32;
        case VALX::Format::A2R10G10B10_UINT_PACK32:
            return VK_FORMAT_A2R10G10B10_UINT_PACK32;
        case VALX::Format::A2R10G10B10_SINT_PACK32:
            return VK_FORMAT_A2R10G10B10_SINT_PACK32;
        case VALX::Format::A2B10G10R10_UNORM_PACK32:
            return VK_FORMAT_A2B10G10R10_UNORM_PACK32;
        case VALX::Format::A2B10G10R10_SNORM_PACK32:
            return VK_FORMAT_A2B10G10R10_SNORM_PACK32;
        case VALX::Format::A2B10G10R10_USCALED_PACK32:
            return VK_FORMAT_A2B10G10R10_USCALED_PACK32;
        case VALX::Format::A2B10G10R10_SSCALED_PACK32:
            return VK_FORMAT_A2B10G10R10_SSCALED_PACK32;
        case VALX::Format::A2B10G10R10_UINT_PACK32:
            return VK_FORMAT_A2B10G10R10_UINT_PACK32;
        case VALX::Format::A2B10G10R10_SINT_PACK32:
            return VK_FORMAT_A2B10G10R10_SINT_PACK32;
        case VALX::Format::R16_UNORM:
            return VK_FORMAT_R16_UNORM;
        case VALX::Format::R16_SNORM:
            return VK_FORMAT_R16_SNORM;
        case VALX::Format::R16_USCALED:
            return VK_FORMAT_R16_USCALED;
        case VALX::Format::R16_SSCALED:
            return VK_FORMAT_R16_SSCALED;
        case VALX::Format::R16_UINT:
            return VK_FORMAT_R16_UINT;
        case VALX::Format::R16_SINT:
            return VK_FORMAT_R16_SINT;
        case VALX::Format::R16_SFLOAT:
            return VK_FORMAT_R16_SFLOAT;
        case VALX::Format::R16G16_UNORM:
            return VK_FORMAT_R16G16_UNORM;
        case VALX::Format::R16G16_SNORM:
            return VK_FORMAT_R16G16_SNORM;
        case VALX::Format::R16G16_USCALED:
            return VK_FORMAT_R16G16_USCALED;
        case VALX::Format::R16G16_SSCALED:
            return VK_FORMAT_R16G16_SSCALED;
        case VALX::Format::R16G16_UINT:
            return VK_FORMAT_R16G16_UINT;
        case VALX::Format::R16G16_SINT:
            return VK_FORMAT_R16G16_SINT;
        case VALX::Format::R16G16_SFLOAT:
            return VK_FORMAT_R16G16_SFLOAT;
        case VALX::Format::R16G16B16_UNORM:
            return VK_FORMAT_R16G16B16_UNORM;
        case VALX::Format::R16G16B16_SNORM:
            return VK_FORMAT_R16G16B16_SNORM;
        case VALX::Format::R16G16B16_USCALED:
            return VK_FORMAT_R16G16B16_USCALED;
        case VALX::Format::R16G16B16_SSCALED:
            return VK_FORMAT_R16G16B16_SSCALED;
        case VALX::Format::R16G16B16_UINT:
            return VK_FORMAT_R16G16B16_UINT;
        case VALX::Format::R16G16B16_SINT:
            return VK_FORMAT_R16G16B16_SINT;
        case VALX::Format::R16G16B16_SFLOAT:
            return VK_FORMAT_R16G16B16_SFLOAT;
        case VALX::Format::R16G16B16A16_UNORM:
            return VK_FORMAT_R16G16B16A16_UNORM;
        case VALX::Format::R16G16B16A16_SNORM:
            return VK_FORMAT_R16G16B16A16_SNORM;
        case VALX::Format::R16G16B16A16_USCALED:
            return VK_FORMAT_R16G16B16A16_USCALED;
        case VALX::Format::R16G16B16A16_SSCALED:
            return VK_FORMAT_R16G16B16A16_SSCALED;
        case VALX::Format::R16G16B16A16_UINT:
            return VK_FORMAT_R16G16B16A16_UINT;
        case VALX::Format::R16G16B16A16_SINT:
            return VK_FORMAT_R16G16B16A16_SINT;
        case VALX::Format::R16G16B16A16_SFLOAT:
            return VK_FORMAT_R16G16B16A16_SFLOAT;
        case VALX::Format::R32_UINT:
            return VK_FORMAT_R32_UINT;
        case VALX::Format::R32_SINT:
            return VK_FORMAT_R32_SINT;
        case VALX::Format::R32_SFLOAT:
            return VK_FORMAT_R32_SFLOAT;
        case VALX::Format::R32G32_UINT:
            return VK_FORMAT_R32G32_UINT;
        case VALX::Format::R32G32_SINT:
            return VK_FORMAT_R32G32_SINT;
        case VALX::Format::R32G32_SFLOAT:
            return VK_FORMAT_R32G32_SFLOAT;
        case VALX::Format::R32G32B32_UINT:
            return VK_FORMAT_R32G32B32_UINT;
        case VALX::Format::R32G32B32_SINT:
            return VK_FORMAT_R32G32B32_SINT;
        case VALX::Format::R32G32B32_SFLOAT:
            return VK_FORMAT_R32G32B32_SFLOAT;
        case VALX::Format::R32G32B32A32_UINT:
            return VK_FORMAT_R32G32B32A32_UINT;
        case VALX::Format::R32G32B32A32_SINT:
            return VK_FORMAT_R32G32B32A32_SINT;
        case VALX::Format::R32G32B32A32_SFLOAT:
            return VK_FORMAT_R32G32B32A32_SFLOAT;
        case VALX::Format::R64_UINT:
            return VK_FORMAT_R64_UINT;
        case VALX::Format::R64_SINT:
            return VK_FORMAT_R64_SINT;
        case VALX::Format::R64_SFLOAT:
            return VK_FORMAT_R64_SFLOAT;
        case VALX::Format::R64G64_UINT:
            return VK_FORMAT_R64G64_UINT;
        case VALX::Format::R64G64_SINT:
            return VK_FORMAT_R64G64_SINT;
        case VALX::Format::R64G64_SFLOAT:
            return VK_FORMAT_R64G64_SFLOAT;
        case VALX::Format::R64G64B64_UINT:
            return VK_FORMAT_R64G64B64_UINT;
        case VALX::Format::R64G64B64_SINT:
            return VK_FORMAT_R64G64B64_SINT;
        case VALX::Format::R64G64B64_SFLOAT:
            return VK_FORMAT_R64G64B64_SFLOAT;
        case VALX::Format::R64G64B64A64_UINT:
            return VK_FORMAT_R64G64B64A64_UINT;
        case VALX::Format::R64G64B64A64_SINT:
            return VK_FORMAT_R64G64B64A64_SINT;
        case VALX::Format::R64G64B64A64_SFLOAT:
            return VK_FORMAT_R64G64B64A64_SFLOAT;
        case VALX::Format::B10G11R11_UFLOAT_PACK32:
            return VK_FORMAT_B10G11R11_UFLOAT_PACK32;
        case VALX::Format::E5B9G9R9_UFLOAT_PACK32:
            return VK_FORMAT_E5B9G9R9_UFLOAT_PACK32;
        case VALX::Format::D16_UNORM:
            return VK_FORMAT_D16_UNORM;
        case VALX::Format::X8_D24_UNORM_PACK32:
            return VK_FORMAT_X8_D24_UNORM_PACK32;
        case VALX::Format::D32_SFLOAT:
            return VK_FORMAT_D32_SFLOAT;
        case VALX::Format::S8_UINT:
            return VK_FORMAT_S8_UINT;
        case VALX::Format::D16_UNORM_S8_UINT:
            return VK_FORMAT_D16_UNORM_S8_UINT;
        case VALX::Format::D24_UNORM_S8_UINT:
            return VK_FORMAT_D24_UNORM_S8_UINT;
        case VALX::Format::D32_SFLOAT_S8_UINT:
            return VK_FORMAT_D32_SFLOAT_S8_UINT;
        case VALX::Format::BC1_RGB_UNORM_BLOCK:
            return VK_FORMAT_BC1_RGB_UNORM_BLOCK;
        case VALX::Format::BC1_RGB_SRGB_BLOCK:
            return VK_FORMAT_BC1_RGB_SRGB_BLOCK;
        case VALX::Format::BC1_RGBA_UNORM_BLOCK:
            return VK_FORMAT_BC1_RGBA_UNORM_BLOCK;
        case VALX::Format::BC1_RGBA_SRGB_BLOCK:
            return VK_FORMAT_BC1_RGBA_SRGB_BLOCK;
        case VALX::Format::BC2_UNORM_BLOCK:
            return VK_FORMAT_BC2_UNORM_BLOCK;
        case VALX::Format::BC2_SRGB_BLOCK:
            return VK_FORMAT_BC2_SRGB_BLOCK;
        case VALX::Format::BC3_UNORM_BLOCK:
            return VK_FORMAT_BC3_UNORM_BLOCK;
        case VALX::Format::BC3_SRGB_BLOCK:
            return VK_FORMAT_BC3_SRGB_BLOCK;
        case VALX::Format::BC4_UNORM_BLOCK:
            return VK_FORMAT_BC4_UNORM_BLOCK;
        case VALX::Format::BC4_SNORM_BLOCK:
            return VK_FORMAT_BC4_SNORM_BLOCK;
        case VALX::Format::BC5_UNORM_BLOCK:
            return VK_FORMAT_BC5_UNORM_BLOCK;
        case VALX::Format::BC5_SNORM_BLOCK:
            return VK_FORMAT_BC5_SNORM_BLOCK;
        case VALX::Format::BC6H_UFLOAT_BLOCK:
            return VK_FORMAT_BC6H_UFLOAT_BLOCK;
        case VALX::Format::BC6H_SFLOAT_BLOCK:
            return VK_FORMAT_BC6H_SFLOAT_BLOCK;
        case VALX::Format::BC7_UNORM_BLOCK:
            return VK_FORMAT_BC7_UNORM_BLOCK;
        case VALX::Format::BC7_SRGB_BLOCK:
            return VK_FORMAT_BC7_SRGB_BLOCK;
            VALX_ASSERT(false && "invalid format");
            return VK_FORMAT_UNDEFINED;
        }
    }
}